import { Point } from "./point";
import { GeoJSONRendererOption } from "./geoJSONRendererOption";
import { DotMapController } from "../../app/src/dotMapController";
export declare class GeoJSONRenderer implements DotMapController {
    private readonly parent;
    private readonly canvas;
    private readonly bufferCanvas;
    private attachingElement;
    private polygons;
    private stageHeight;
    private stageWidth;
    private stageX;
    private stageY;
    private option;
    private anchorPoints;
    private zoom;
    mouseRatioX: number;
    mouseRatioY: number;
    offsetX: number;
    offsetY: number;
    startClientX: number;
    startClientY: number;
    image: HTMLImageElement;
    get pixelAndGapSize(): number;
    get pixelSize(): number;
    get gapSize(): number;
    constructor(attachingElement: HTMLElement, geoJsonRendererOption: GeoJSONRendererOption);
    private loadGeoJson;
    private initHTML;
    private initInteraction;
    private initImage;
    private resizeStage;
    private resizePolygons;
    private makeDots;
    run: () => void;
    resize: () => void;
    draw: () => void;
    drawAnchors: () => void;
    move: (moveY: number, moveX: number) => void;
    onMouseMove: (event: MouseEvent) => void;
    onWheel: (event: WheelEvent) => void;
    onMoveMouse: (event: MouseEvent) => void;
    onMouseDown: (event: MouseEvent) => void;
    onMouseUp: (event: MouseEvent) => void;
    addZoom: (zoom: number) => void;
    addAnchors: (points: Point[] | Point) => void;
}
