import { Canvas } from '@dot-map-renderer/component';
import { IRendererOption } from './IRendererOption';
import { IRenderer } from './IRenderer';
import { RendererContext } from './RendererContext';
import { Layer } from './Layer';
import { AnimationManager } from './AnimationManager';
export declare class CanvasRenderer implements IRenderer {
  private readonly layers;
  readonly bufferCanvas: Canvas;
  private attachingElement;
  canvas: Canvas;
  parent: HTMLElement;
  option: IRendererOption;
  stageHeight: number;
  stageWidth: number;
  stageX: number;
  stageY: number;
  zoom: number;
  animation?: AnimationManager;
  get pixelAndGapSize(): number;
  get pixelSize(): number;
  get gapSize(): number;
  get canvasOffsetWidth(): number;
  get canvasOffsetHeight(): number;
  constructor(attachingElement: HTMLElement, rendererOption: IRendererOption);
  private initHTML;
  private initLayer;
  private resizeStage;
  resize: () => void;
  draw: () => void;
  getContext: () => RendererContext;
  getLayer: <T extends Layer = Layer>(layerKey: string) => T;
  refresh: () => void;
  remove(): void;
}
